name: Cypress Tests

on: 
 push:
   branches:
     - master
jobs:
  cypress:
    run-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install Dep
        uses: npm install
      - name: Run Cypress test
        uses: npm run test:e2e         