name: Cypress Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Install Dep
        run: npm install

      - name: Build app
        run: npm run build  

      - name: Run Cypress test
        run: npm run test:e2e         